language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnfc*
install: 
  - python3 setup.py install
  - pip install codecov
  - pip install stdeb
# command to run tests
script: 
  - python3 -c "from pynfc import pynfc; ll = pynfc.PosixLibraryLoader(); print(list(ll.getpaths('nfc')))" # Debugging travis
  - nosetests --with-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python3 setup.py --command-packages=stdeb.command bdist_deb
