dist: trusty
sudo: required
language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnfc5
install: 
  - python3 setup.py install
  - pip install codecov
  - pip install stdeb
# command to run tests
script:
  - nosetests --with-coverage
  - sudo python3 setup.py --command-packages=stdeb.command bdist_deb
after_success:
  - bash <(curl -s https://codecov.io/bash)
